name: Publish Docker image

on:
  push:
    branches:
      - master
      - main
      
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        id: docker-login
        uses: docker/login-action@latest
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@latest
        with:
          images: dewab/sonarr-radarr-queue-cleaner
      
      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@latest
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
