name: Publish Docker image

on:
  push:
    branches:
      - master
      - main
      
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        id: ghcr-login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
